# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module TreeStand::Node::TreeSitter::Node; end
module TreeStand::Node::TreeSitter::Query; end
module TreeStand::Parser::TreeSitter::Language; end
module TreeStand::Parser::TreeSitter::Parser; end
module TreeStand::Tree::TreeSitter::Tree; end
