name: TreeStand
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        entry:
          - { ruby: 3.0 }
          - { ruby: 3.1 }
    name: test (${{ matrix.entry.ruby }})
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          name: DerekStride/tree-sitter-sql
          path: tmp

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.entry.ruby }}
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
          restore-keys: ${{ runner.os }}-gems-

      - run: sudo apt-get install -y libtree-sitter-dev
      - run: bundle install --jobs=3 --retry=3 --path=vendor/bundle
      - run: bin/setup
      - run: bundle exec rake
