name: Publish docs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish documentation website
    steps:
      - uses: actions/checkout@v3

      - name: Setup TreeSitter
        run: sudo apt-get install -y libtree-sitter-dev make gcc

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Generate documentation
        run: bundle exec yard --output-dir docs

      - name: Commit to gh-pages
        run: |
          git add docs
          git commit -m "Publish website $(git log --format=format:%h -1)"
          git push --force origin main:gh-pages
